### ISSUE TITLE
AttributeError: 'QMenuBar' object has no attribute 'setTabletTracking' ???

### ISSUE THREAD

**Issue by ithjz** [PerpetualSmile/BeautyCamera#2]
Traceback (most recent call last):
  File "E:\users\administrator\eclipse-workspace2\BeautyCamera-master\main.py", line 593, in <module>
    MainWindow()
  File "E:\users\administrator\eclipse-workspace2\BeautyCamera-master\main.py", line 22, in __init__
    self.ui.setupUi(MainWindow)
  File "E:\users\administrator\eclipse-workspace2\BeautyCamera-master\window.py", line 804, in setupUi
    self.menubar.setTabletTracking(False)
AttributeError: 'QMenuBar' object has no attribute 'setTabletTracking'

**Comment by ghost** [comment]
注释掉window.py的第804行self.menubar.setTabletTracking(False)即可。
